/*

This is a JavaScript file you can edit to add custom markers to the map.
uNmINeD does not overwrite this file during map generation.

Steps:

    1. Edit this file using Notepad or a code editor (do not use document editors like Microsoft Word)
    2. Change the line "isEnabled: false," to "isEnabled: true," to display the markers
    3. Change or remove the example markers
    4. Add your own markers

Marker format:

    {
        x: X coordinate of the marker (in Minecraft block units),
        z: Z coordinate of the marker (in Minecraft block units),
        image: marker image URL to display (in quotes),
        imageScale: scale of the image (e.g. 1 = display full size, 0.5 = display half size),
        imageAnchor: [0.5, 1] means the tip of the pin is at the center-bottom of the image (see OpenLayers documentation for more info),
        text: marker text do display (in quotes),
        textColor: text color in HTML/CSS format (in quotes),
        offsetX: horizontal pixel offset of the text,
        offsetY: vertical pixel offset of the text,
        font: text font in HTML/CSS format (in quotes),
    },

Things to keep in mind:

* There are opening and closing brackets for each marker "{" and "}"
* Property names are case sensitive (i.e. "textColor" is okay, "TextColor" is not)
* There is a comma (",") at the end of each line except the opening brackets ("{")

You can use https://mapmarker.io/editor to generate custom pin images.
Use the imageScale property if the pin image is too large.

*/

UnminedCustomMarkers = {

    isEnabled: true,

    markers: [

        {
            x: -186,
            z: 87,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Gas",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },

        {
            x: -4127,
            z: -2736,
            image: "zone7.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Nether City z7", 
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },

        {
            x: -3970,
            z: -4370,
            image: "zone7.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Military Base", 
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },

        {
            x: -1198,
            z: -4143,
            image: "zone6.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Airbase", 
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
		
		        {
            x: 2527,
            z: -2260,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Port", 
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
		
		        {
            x: 2472,
            z: -4681,
            image: "zone7.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Snow Neighborhood", 
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
		
		        {
            x: 2604,
            z: -3831,
            image: "zone6.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Ski Resort/cabins", 
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
		
		        {
            x: 3157,
            z: -2561,
            image: "zone6.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Snow City", 
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
		        {
            x: 2368,
            z: -2570,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Airport", 
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
		        {
            x: 2117,
            z: -2318,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Rail Yard", 
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
		        {
            x: 4220,
            z: -2858,
            image: "zone6.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Snow City", 
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
		        // OG MARKERS
        {
            x: 1521,
            z: -4167,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Plane Crash",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 4766,
            z: -4628,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Missile Silo",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 2130,
            z: -181,
            image: "zone6.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Area 51",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2183,
            z: -4560,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Submarine",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -1260,
            z: -2010,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Mine Plant",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 320,
            z: -2490,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Open Pit Mine",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 65,
            z: 778,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 3266,
            z: -574,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Dam",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 3645,
            z: -1058,
            image: "zone6.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Atlantis",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 1429,
            z: 610,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Ruins",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 4260,
            z: 292,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Casino",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 3814,
            z: 139,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Mountain City",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 4195,
            z: 1213,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Water Plant",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 4292,
            z: 1765,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Solar Farm",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 4129,
            z: 3738,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Dune Ruins",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 1876,
            z: 2757,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Nuclear Power Plant",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 2572,
            z: 4582,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Missile Silo",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 1677,
            z: 3709,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Military Base",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 1729,
            z: 4523,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Black Site",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -678,
            z: 4526,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Old Farm",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 2326,
            z: 2041,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Crater",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -90,
            z: 2811,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Big Farm",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -3910,
            z: 4046,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Western Town",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -3275,
            z: 4470,
            image: "zone2.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Abandoned Houses",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -635,
            z: 3473,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Medium City",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -4809,
            z: 4,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Pier",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -4785,
            z: 726,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "beach neighborhoods",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -4027,
            z: 1835,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Suburbs",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2835,
            z: 1468,
            image: "zone6.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "The Hood z6",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2605,
            z: 2205,
            image: "zone2.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Rural Hood z2",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2618,
            z: 1053,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "City Rail Yard",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2832,
            z: 455,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "CDC Labs",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -1888,
            z: -561,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "City Airport",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -1466,
            z: 446,
            image: "zone6.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Industrial",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -1570,
            z: 1811,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Outlet Mall",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -3794,
            z: -542,
            image: "zone6.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Downtown",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -3650,
            z: 180,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Midtown",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -11226,
            z: 11213,
            image: "zone1.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Spawn",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2875,
            z: -477,
            image: "zone2.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "University",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2449,
            z: -1648,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Light House",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -4389,
            z: -883,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Tech Plaza",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -4749,
            z: -685,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Beach Front",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -3163,
            z: -1329,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Marina",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2771,
            z: -2796,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Island",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 560,
            z: 4398,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Oil Refinery",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 592,
            z: 3310,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Oil Fields",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 1516,
            z: 1791,
            image: "norad.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "NORAD",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -239,
            z: -1137,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 1605,
            z: 3106,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 4316,
            z: 2638,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 3133,
            z: 1714,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 4289,
            z: -599,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 4969,
            z: -2779,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2025,
            z: 4074,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -3873,
            z: -346,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2057,
            z: 1334,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -4293,
            z: 2777,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -3984,
            z: -2985,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -3584,
            z: -4492,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -1309,
            z: -4312,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 1518,
            z: 1514,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 2742,
            z: -4662,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -314,
            z: 1565,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Caves",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -3721,
            z: 990,
            image: "radio.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Radio Tower",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -4246,
            z: 213,
            image: "zone3.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Big Park",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2935,
            z: -1207,
            image: "zone5.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Coast Guard",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -2367,
            z: -31,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Data Center",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 4635,
            z: -1880,
            image: "zone4.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Underground Mine",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -4067,
            z: -3726,
            image: "norad.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "NORAD",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 4295,
            z: -4335,
            image: "norad.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "NORAD",
            textColor: "red", 
            offsetX: 0,
            offsetY: -53,
            font: "bold 20px Calibri,sans serif",
        },
        // do not delete the following two closing brackets
    ]
}